In [ ]:
from keras.models import load_model  # TensorFlow is required for Keras to work
import cv2  # Install opencv-python
import numpy as np

# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = load_model("keras_model.h5", compile=False)

# Load the labels
class_names = open("labels.txt", "r").readlines()

# CAMERA can be 0 or 1 based on default camera of your computer
camera = cv2.VideoCapture(0)

while True:
    # Grab the webcamera's image.
    ret, image = camera.read()

    # Resize the raw image into (224-height,224-width) pixels
    image = cv2.resize(image, (224, 224), interpolation=cv2.INTER_AREA)

    # Show the image in a window
    cv2.imshow("Webcam Image", image)

    # Make the image a numpy array and reshape it to the models input shape.
    image = np.asarray(image, dtype=np.float32).reshape(1, 224, 224, 3)

    # Normalize the image array
    image = (image / 127.5) - 1

    # Predicts the model
    prediction = model.predict(image)
    index = np.argmax(prediction)
    class_name = class_names[index]
    confidence_score = prediction[0][index]

    # Print prediction and confidence score
    print("Class:", class_name[2:], end="")
    print("Confidence Score:", str(np.round(confidence_score * 100))[:-2], "%")

    # Listen to the keyboard for presses.
    keyboard_input = cv2.waitKey(1)

    # 27 is the ASCII for the esc key on your keyboard.
    if keyboard_input == 27:
        break

camera.release()
cv2.destroyAllWindows()


1/1 [==============================] - 1s 555ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 16ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 18ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 25ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 21ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 21ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 20ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 21ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 21ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 21ms/step
Class: abungo
Confidence Score: 100 %
1/1 [==============================] - 0s 18ms/step
Class: abungo
Confidence Score: 100 %
1/1 [====

In [2]:
# !pip install opencv-python

In [16]:
camera = cv2.VideoCapture(0)
ret, image = camera.read()
print(image)

[[[183 170 188]
  [185 173 191]
  [184 174 190]
  ...
  [158 144 166]
  [157 143 165]
  [157 143 165]]

 [[180 167 185]
  [183 171 189]
  [183 173 189]
  ...
  [154 141 163]
  [156 143 165]
  [160 147 169]]

 [[179 166 184]
  [181 169 187]
  [182 172 188]
  ...
  [153 141 163]
  [154 142 164]
  [159 147 169]]

 ...

 [[ 29  26  26]
  [ 29  26  26]
  [ 29  26  26]
  ...
  [ 41  46  42]
  [ 48  51  48]
  [ 49  52  49]]

 [[ 27  24  27]
  [ 29  26  29]
  [ 30  27  29]
  ...
  [ 43  48  43]
  [ 47  52  47]
  [ 50  55  50]]

 [[ 25  21  27]
  [ 27  23  28]
  [ 30  27  30]
  ...
  [ 45  50  45]
  [ 45  51  46]
  [ 48  54  49]]]


In [2]:
from keras.models import load_model  # TensorFlow is required for Keras to work
import cv2  # Install opencv-python
import numpy as np

# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = load_model("keras_model.h5", compile=False)
    

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x0000018AB5455420>>

In [4]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_1 (Sequential)   (None, 1280)              410208    
                                                                 
 sequential_3 (Sequential)   (None, 2)                 128300    
                                                                 
Total params: 538,508
Trainable params: 524,428
Non-trainable params: 14,080
_________________________________________________________________
